/// ============================================================================
/// PROFILE MODEL - DATA CLASS WITH JSON SERIALIZATION
/// ============================================================================
/// 
/// PURPOSE: Represent user profile data from database
/// 
/// LEARNING OBJECTIVES:
/// 1. Understand data models in Flutter
/// 2. Learn JSON serialization (fromJson, toJson)
/// 3. Use copyWith for immutable updates
/// 4. Handle nullable fields properly
///
/// KEY CONCEPTS:
/// - Immutable data classes
/// - Factory constructors for JSON
/// - Equatable for value equality
/// - DateTime handling
///
/// ============================================================================

import 'package:equatable/equatable.dart';

/// User Profile Model
/// 
/// Represents a user's profile information stored in the database.
/// 
/// **Database Schema:**
/// ```sql
/// profiles (
///   id uuid PRIMARY KEY,
///   user_id uuid REFERENCES auth.users,
///   full_name text NOT NULL,
///   bio text,
///   avatar_url text,
///   phone text,
///   date_of_birth date,
///   created_at timestamp,
///   updated_at timestamp
/// )
/// ```
/// 
/// **Why Immutable?**
/// - Predictable (can't change unexpectedly)
/// - Thread-safe
/// - Easy to test
/// - Flutter optimizes rebuilds with immutable data
/// 
/// **Why Equatable?**
/// - Compare profiles by value, not reference
/// - Prevents unnecessary UI rebuilds
/// - Makes testing easier
class Profile extends Equatable {
  // -------------------------------------------------------------------------
  // PROPERTIES
  // -------------------------------------------------------------------------
  
  /// Unique identifier for this profile
  /// Generated by database (UUID format)
  final String id;
  
  /// Foreign key to auth.users table
  /// Links profile to authenticated user
  /// One user can have only ONE profile
  final String userId;
  
  /// User's full name (REQUIRED)
  /// Example: "John Doe"
  final String fullName;
  
  /// Short bio/description (OPTIONAL)
  /// Example: "Flutter developer and coffee enthusiast"
  /// Max recommended: 160 characters
  final String? bio;
  
  /// URL to profile picture (OPTIONAL)
  /// Can be Supabase storage URL or external URL
  /// Example: "https://storage.supabase.co/..."
  final String? avatarUrl;
  
  /// Phone number (OPTIONAL)
  /// Example: "+1 234 567 8900"
  /// Store in E.164 format for consistency
  final String? phone;
  
  /// User's date of birth (OPTIONAL)
  /// Used for age calculation, birthday notifications
  final DateTime? dateOfBirth;
  
  /// When this profile was created
  /// Auto-set by database on INSERT
  final DateTime createdAt;
  
  /// Last time profile was updated
  /// Auto-updated by database on UPDATE
  final DateTime updatedAt;
  
  // -------------------------------------------------------------------------
  // CONSTRUCTOR
  // -------------------------------------------------------------------------
  
  /// Creates a Profile instance
  /// 
  /// **Required fields:**
  /// - id, userId, fullName, createdAt, updatedAt
  /// 
  /// **Optional fields:**
  /// - bio, avatarUrl, phone, dateOfBirth
  /// 
  /// Example:
  /// ```dart
  /// final profile = Profile(
  ///   id: '123-456',
  ///   userId: '789-012',
  ///   fullName: 'John Doe',
  ///   bio: 'Flutter developer',
  ///   createdAt: DateTime.now(),
  ///   updatedAt: DateTime.now(),
  /// );
  /// ```
  const Profile({
    required this.id,
    required this.userId,
    required this.fullName,
    this.bio,
    this.avatarUrl,
    this.phone,
    this.dateOfBirth,
    required this.createdAt,
    required this.updatedAt,
  });
  
  // -------------------------------------------------------------------------
  // JSON SERIALIZATION
  // -------------------------------------------------------------------------
  
  /// Creates Profile from JSON (API response → Dart object)
  /// 
  /// **When to use:**
  /// When receiving data from Supabase API
  /// 
  /// **Example JSON:**
  /// ```json
  /// {
  ///   "id": "123-456",
  ///   "user_id": "789-012",
  ///   "full_name": "John Doe",
  ///   "bio": "Flutter developer",
  ///   "avatar_url": null,
  ///   "phone": "+1234567890",
  ///   "date_of_birth": "1990-01-15",
  ///   "created_at": "2025-12-01T10:00:00Z",
  ///   "updated_at": "2026-01-08T15:30:00Z"
  /// }
  /// ```
  /// 
  /// **How it works:**
  /// 1. Reads JSON map
  /// 2. Extracts each field
  /// 3. Converts types (String → DateTime)
  /// 4. Handles nullable fields
  /// 5. Returns Profile instance
  factory Profile.fromJson(Map<String, dynamic> json) {
    return Profile(
      // REQUIRED FIELDS
      // Cast to String for type safety
      id: json['id'] as String,
      userId: json['user_id'] as String,
      fullName: json['full_name'] as String,
      
      // OPTIONAL STRING FIELDS
      // If null in JSON, stays null
      bio: json['bio'] as String?,
      avatarUrl: json['avatar_url'] as String?,
      phone: json['phone'] as String?,
      
      // OPTIONAL DATE FIELD
      // Convert string to DateTime if present
      // "1990-01-15" → DateTime(1990, 1, 15)
      dateOfBirth: json['date_of_birth'] != null
          ? DateTime.parse(json['date_of_birth'] as String)
          : null,
      
      // REQUIRED TIMESTAMP FIELDS
      // ISO 8601 format: "2026-01-08T15:30:00Z"
      // DateTime.parse() handles timezone automatically
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }
  
  /// Converts Profile to JSON (Dart object → API format)
  /// 
  /// **When to use:**
  /// When sending data to Supabase API (CREATE, UPDATE)
  /// 
  /// **Returns:**
  /// ```json
  /// {
  ///   "id": "123-456",
  ///   "user_id": "789-012",
  ///   "full_name": "John Doe",
  ///   "bio": "Flutter developer",
  ///   "avatar_url": null,
  ///   "phone": "+1234567890",
  ///   "date_of_birth": "1990-01-15",
  ///   "created_at": "2025-12-01T10:00:00.000Z",
  ///   "updated_at": "2026-01-08T15:30:00.000Z"
  /// }
  /// ```
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'full_name': fullName,
      'bio': bio,
      'avatar_url': avatarUrl,
      'phone': phone,
      // Convert DateTime to date-only string
      // DateTime(1990, 1, 15) → "1990-01-15"
      'date_of_birth': dateOfBirth?.toIso8601String().split('T')[0],
      // Convert DateTime to ISO 8601 string
      // DateTime(2026, 1, 8, 15, 30) → "2026-01-08T15:30:00.000Z"
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
  
  // -------------------------------------------------------------------------
  // COPY WITH - IMMUTABLE UPDATES
  // -------------------------------------------------------------------------
  
  /// Creates a copy of this profile with some fields changed
  /// 
  /// **Why needed?**
  /// Profile is immutable (final fields)
  /// Can't do: `profile.fullName = "New Name"` ❌
  /// Must do: `profile = profile.copyWith(fullName: "New Name")` ✅
  /// 
  /// **When to use:**
  /// - Updating profile after edit
  /// - Changing single field
  /// - Creating modified version for testing
  /// 
  /// **Example:**
  /// ```dart
  /// final original = Profile(...);
  /// 
  /// // Update just the bio
  /// final updated = original.copyWith(bio: 'New bio');
  /// 
  /// // Update multiple fields
  /// final updated2 = original.copyWith(
  ///   fullName: 'Jane Doe',
  ///   phone: '+9876543210',
  ///   updatedAt: DateTime.now(),
  /// );
  /// ```
  /// 
  /// **How it works:**
  /// - Takes new values for fields you want to change
  /// - Uses `??` operator: newValue ?? this.oldValue
  /// - Returns NEW Profile with changes
  /// - Original profile unchanged
  Profile copyWith({
    String? id,
    String? userId,
    String? fullName,
    String? bio,
    String? avatarUrl,
    String? phone,
    DateTime? dateOfBirth,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Profile(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      fullName: fullName ?? this.fullName,
      bio: bio ?? this.bio,
      avatarUrl: avatarUrl ?? this.avatarUrl,
      phone: phone ?? this.phone,
      dateOfBirth: dateOfBirth ?? this.dateOfBirth,
      createdAt: createdAt ?? this.createdAt,
      // Usually update timestamp when copying
      updatedAt: updatedAt ?? DateTime.now(),
    );
  }
  
  // -------------------------------------------------------------------------
  // EQUATABLE
  // -------------------------------------------------------------------------
  
  /// Properties used for equality comparison
  /// 
  /// **Why Equatable?**
  /// ```dart
  /// // WITHOUT Equatable:
  /// final p1 = Profile(id: '1', ...);
  /// final p2 = Profile(id: '1', ...); // Same data
  /// print(p1 == p2); // false ❌ (different objects)
  /// 
  /// // WITH Equatable:
  /// print(p1 == p2); // true ✅ (same values)
  /// ```
  /// 
  /// **Impact:**
  /// - BlocBuilder won't rebuild if profile values unchanged
  /// - Tests can compare profiles easily
  /// - Better performance
  @override
  List<Object?> get props => [
        id,
        userId,
        fullName,
        bio,
        avatarUrl,
        phone,
        dateOfBirth,
        createdAt,
        updatedAt,
      ];
}

// ============================================================================
// SUMMARY OF WHAT WE LEARNED:
// ============================================================================
//
// 1. DATA MODELS:
//    - Represent database tables as Dart classes
//    - Immutable (final fields)
//    - Type-safe (String, DateTime, etc.)
//
// 2. JSON SERIALIZATION:
//    - fromJson(): API response → Dart object
//    - toJson(): Dart object → API format
//    - Handle type conversions (String → DateTime)
//    - Handle nullable fields
//
// 3. COPY WITH:
//    - Update immutable objects
//    - Returns new instance with changes
//    - Original unchanged
//    - Essential for state management
//
// 4. EQUATABLE:
//    - Compare by value, not reference
//    - Prevents unnecessary rebuilds
//    - Makes testing easier
//    - Define equality with props
//
// 5. DATETIME HANDLING:
//    - Parse ISO 8601 strings
//    - Format for API
//    - Date-only formatting
//    - Timezone awareness
//
// 6. NULLABLE TYPES:
//    - String? = can be null
//    - Required vs optional fields
//    - Handle nulls in JSON
//    - Default to null if missing
//
// ============================================================================
