/// ============================================================================
/// MESSAGE MODEL - DATA REPRESENTATION FOR CHAT MESSAGES
/// ============================================================================
/// 
/// PURPOSE: Represent a single message in a conversation
/// 
/// LEARNING OBJECTIVES:
/// 1. Model design for messaging
/// 2. JSON serialization patterns
/// 3. Nullable vs non-nullable fields
/// 4. Immutable data classes
///
/// ============================================================================

import 'package:equatable/equatable.dart';

/// Message - Represents a single chat message
/// 
/// **Immutable**: Once created, cannot be changed
/// **Equatable**: Can compare messages by value (for BLoC)
/// 
/// **Fields:**
/// - id: Unique message identifier (from database)
/// - chatId: Conversation this message belongs to
/// - senderId: Who sent the message
/// - receiverId: Who receives the message
/// - message: Text content (nullable - could be media-only)
/// - mediaUrl: URL to media file (nullable - could be text-only)
/// - createdAt: When message was sent (server timestamp)
/// - updatedAt: When message was last modified
class Message extends Equatable {
  /// Unique message ID (generated by database)
  final String id;
  
  /// Chat/conversation ID (deterministic from user IDs)
  final String chatId;
  
  /// User who sent the message
  final String senderId;
  
  /// User who receives the message
  final String receiverId;
  
  /// Text message content (nullable)
  /// Can be null for media-only messages
  final String? message;
  
  /// URL to media in Supabase Storage (nullable)
  /// Can be null for text-only messages
  final String? mediaUrl;
  
  /// Server timestamp when message was created
  final DateTime createdAt;
  
  /// Server timestamp when message was last updated
  final DateTime updatedAt;

  /// Timestamp when message was delivered (nullable)
  final DateTime? deliveredAt;

  /// Timestamp when message was read (nullable)
  final DateTime? readAt;
  
  /// Constructor
  const Message({
    required this.id,
    required this.chatId,
    required this.senderId,
    required this.receiverId,
    this.message,
    this.mediaUrl,
    required this.createdAt,
    required this.updatedAt,
    this.deliveredAt,
    this.readAt,
  });
  
  // =========================================================================
  // JSON SERIALIZATION
  // =========================================================================
  
  /// Create Message from JSON (from Supabase)
  /// 
  /// **Used when:**
  /// - Fetching messages from database
  /// - Receiving realtime updates
  /// 
  /// **Example JSON:**
  /// ```json
  /// {
  ///   "id": "abc123",
  ///   "chat_id": "xyz789",
  ///   "sender_id": "user1",
  ///   "receiver_id": "user2",
  ///   "message": "Hello!",
  ///   "media_url": null,
  ///   "created_at": "2024-01-15T12:00:00Z",
  ///   "updated_at": "2024-01-15T12:00:00Z"
  /// }
  /// ```
  factory Message.fromJson(Map<String, dynamic> json) {
    return Message(
      id: json['id'] as String,
      chatId: json['chat_id'] as String,
      senderId: json['sender_id'] as String,
      receiverId: json['receiver_id'] as String,
      message: json['message'] as String?,
      mediaUrl: json['media_url'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
      deliveredAt: json['delivered_at'] != null 
          ? DateTime.parse(json['delivered_at'] as String) 
          : null,
      readAt: json['read_at'] != null 
          ? DateTime.parse(json['read_at'] as String) 
          : null,
    );
  }
  
  /// Convert Message to JSON (for sending to Supabase)
  /// 
  /// **Used when:**
  /// - Creating new message
  /// - Updating existing message
  /// 
  /// **Note**: 
  /// - id might be empty for new messages (database generates it)
  /// - timestamps are server-generated (use NOW())
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'chat_id': chatId,
      'sender_id': senderId,
      'receiver_id': receiverId,
      'message': message,
      'media_url': mediaUrl,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
      'delivered_at': deliveredAt?.toIso8601String(),
      'read_at': readAt?.toIso8601String(),
    };
  }
  
  // =========================================================================
  // HELPER METHODS
  // =========================================================================
  
  /// Check if this is a text message
  bool get isTextMessage => message != null && message!.isNotEmpty;
  
  /// Check if this is a media message
  bool get isMediaMessage => mediaUrl != null && mediaUrl!.isNotEmpty;
  
  /// Check if message was sent by specific user
  bool isSentBy(String userId) => senderId == userId;
  
  /// Check if message was received by specific user
  bool isReceivedBy(String userId) => receiverId == userId;
  
  /// Check if user is participant in this message
  bool involvesUser(String userId) {
    return senderId == userId || receiverId == userId;
  }

  /// Message status helpers
  bool get isDelivered => deliveredAt != null;
  bool get isRead => readAt != null;
  bool get isPending => !isDelivered && !isRead;

  /// Get message status text
  String get statusText {
    if (isRead) return 'Read';
    if (isDelivered) return 'Delivered';
    return 'Sent';
  }
  
  // =========================================================================
  // EQUATABLE (for BLoC state comparison)
  // =========================================================================
  
  /// Properties used for equality comparison
  /// Two messages are equal if they have the same id
  @override
  List<Object?> get props => [
        id,
        chatId,
        senderId,
        receiverId,
        message,
        mediaUrl,
        createdAt,
        updatedAt,
        deliveredAt,
        readAt,
      ];
  
  // =========================================================================
  // COPYWITH (for updates)
  // =========================================================================
  
  /// Create a copy with some fields updated
  /// 
  /// **Used for:**
  /// - Optimistic updates (mark as sending, then sent)
  /// - Edit message
  /// - Update timestamps
  /// 
  /// **Example:**
  /// ```dart
  /// final updated = message.copyWith(
  ///   message: 'Edited message',
  ///   updatedAt: DateTime.now(),
  /// );
  /// ```
  Message copyWith({
    String? id,
    String? chatId,
    String? senderId,
    String? receiverId,
    String? message,
    String? mediaUrl,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? deliveredAt,
    DateTime? readAt,
  }) {
    return Message(
      id: id ?? this.id,
      chatId: chatId ?? this.chatId,
      senderId: senderId ?? this.senderId,
      receiverId: receiverId ?? this.receiverId,
      message: message ?? this.message,
      mediaUrl: mediaUrl ?? this.mediaUrl,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      deliveredAt: deliveredAt ?? this.deliveredAt,
      readAt: readAt ?? this.readAt,
    );
  }
  
  // =========================================================================
  // DEBUG
  // =========================================================================
  
  @override
  String toString() {
    return 'Message(id: $id, from: $senderId, to: $receiverId, '
        'text: ${message?.substring(0, message!.length > 20 ? 20 : message!.length) ?? 'null'}, '
        'media: ${mediaUrl != null ? 'yes' : 'no'})';
  }
}

// ============================================================================
// USAGE EXAMPLES
// ============================================================================
//
// 1. CREATE TEXT MESSAGE:
// ```dart
// final message = Message(
//   id: '',  // Empty - database will generate
//   chatId: chatId,
//   senderId: currentUserId,
//   receiverId: otherUserId,
//   message: 'Hello, how are you?',
//   mediaUrl: null,
//   createdAt: DateTime.now(),
//   updatedAt: DateTime.now(),
// );
// ```
//
// 2. CREATE MEDIA MESSAGE:
// ```dart
// final mediaMessage = Message(
//   id: '',
//   chatId: chatId,
//   senderId: currentUserId,
//   receiverId: otherUserId,
//   message: null,
//   mediaUrl: 'https://storage.supabase.co/...',
//   createdAt: DateTime.now(),
//   updatedAt: DateTime.now(),
// );
// ```
//
// 3. FROM DATABASE:
// ```dart
// final json = await supabase.from('messages').select().single();
// final message = Message.fromJson(json);
// ```
//
// 4. TO DATABASE:
// ```dart
// await supabase.from('messages').insert(message.toJson());
// ```
//
// 5. CHECK MESSAGE TYPE:
// ```dart
// if (message.isTextMessage) {
//   print('Text: ${message.message}');
// } else if (message.isMediaMessage) {
//   print('Media: ${message.mediaUrl}');
// }
// ```
//
// ============================================================================
